In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [9]:
a = 2
epsilon = np.array([
10 ** p
for p in np.arange(0, -11, -1, dtype = float)])
epsilon

array([1.e+00, 1.e-01, 1.e-02, 1.e-03, 1.e-04, 1.e-05, 1.e-06, 1.e-07,
       1.e-08, 1.e-09, 1.e-10])

In [8]:

x = np.append(a - epsilon, (a + epsilon)[::-1])
x

array([1.        , 1.9       , 1.99      , 1.999     , 1.9999    ,
       1.99999   , 1.999999  , 1.9999999 , 1.99999999, 2.        ,
       2.        , 2.        , 2.        , 2.00000001, 2.0000001 ,
       2.000001  , 2.00001   , 2.0001    , 2.001     , 2.01      ,
       2.1       , 3.        ])

In [5]:
np.array([1, 2, 3]) + 6

array([7, 8, 9])

In [7]:
[1, 2, 3] + [6]

[1, 2, 3, 6]

In [10]:
x = np.array([[1, 2],[3, 5] ])
x


array([[1, 2],
       [3, 5]])

In [11]:
x - 1

array([[0, 1],
       [2, 4]])

In [12]:
x.T

array([[1, 3],
       [2, 5]])

In [13]:
x.dot(x)

array([[ 7, 12],
       [18, 31]])

In [14]:
x * x

array([[ 1,  4],
       [ 9, 25]])

In [15]:
y = lambda x: x ** 2 + e ** x

In [20]:
np.append([1,3,4], [4], [5])

TypeError: 'list' object cannot be interpreted as an integer

In [32]:
np.array(range(4)) - np.array(range(0, -4, -1))

array([0, 2, 4, 6])

array([-1.        , -0.95833333, -0.91666667, -0.875     , -0.83333333,
       -0.79166667, -0.75      , -0.70833333, -0.66666667, -0.625     ,
       -0.58333333, -0.54166667, -0.5       , -0.45833333, -0.41666667,
       -0.375     , -0.33333333, -0.29166667, -0.25      , -0.20833333,
       -0.16666667, -0.125     , -0.08333333, -0.04166667, -0.        ])